# Site settings
title: Hicham B.I.
email: Hicham.Bouzidi@gmail.com
description: Hicham Bouzidi Idrissi Personal Blog.
baseurl: ""
url: ""
github_username: HichamBI
paginate: 4
paginate_path: /blog/page/:num/

# Build settings
markdown: kramdown